name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        perl-version:
          - '5.10'
          - '5.16'
          - 'latest'

    container:
      image: perl:${{ matrix.perl-version }}

    steps:
      - uses: actions/checkout@v1
      - name: perl -V
        run: perl -V
      - name: Install Dependencies
        run: cpanm -iq File::Spec ExtUtils::MakeMaker && cpanm -iq --installdeps --notest .
      - name: Run Tests
        run: prove -l t
